### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by octavonce** [purpleprotocol/graphlib#1]
Before optimizing the code any further we should add benchmarks in order to not do it blindly.

**Comment by sn99** [comment]
Do you wanna use an external crate like [criterion.rs](https://github.com/bheisler/criterion.rs) (builds on stable) or language internals like [test](https://doc.rust-lang.org/1.15.1/book/benchmark-tests.html) (can only work only on nightly currently) ?

I personally think [criterion.rs](https://github.com/bheisler/criterion.rs) is better

**Comment by octavonce** [comment]
Yes, let's do it with criterion.
