### ISSUE TITLE
Add support for a topological ordering

### ISSUE THREAD

**Issue by garyanaplan** [purpleprotocol/graphlib#26]
Topological ordering (https://en.wikipedia.org/wiki/Topological_sorting) is useful for a Graph Library.

I've got an implementation of Kahn's algorithm which is based on the approach you used for your current Dfs implementation. Would you like me to create a PR?

**Comment by octavonce** [comment]
@garyanaplan Yes, you are welcome to do so! A topological sort would be a good addition to the api.

**Comment by octavonce** [comment]
Resolved in #27
