### ISSUE TITLE
Some library feedback

### ISSUE THREAD

**Issue by adinapoli-mndc** [purpleprotocol/graphlib#31]
Hey @octavonce !

First of all, thank you so much for putting the time and effort to release the library in the wild. I was on the hunt for a graph library while evaluating alternatives to `petgraph` and this one has been on my radar for a while now, and looks very promising 😉 

I have some (unsolicited 😁 ) feedback which I hope you might find useful. In particular:

1. It would be very nice to be able to have edges as "first class" citizens of the library. At the 
    moment one can only add a "plain" edge or a weighted one, but using an `f32` is a bit
    limiting, as users might want to embed arbitrary metadata at the edge level. Have you ever
    thought about parametrising your `Graph` over some edge type `E`? If so, how did it go?

2. In some circumstances, it might be necessary to allow parallel edges between nodes. At
    the moment, if I understand correctly, `add_edge` is idempotent and cannot create more
    than one edge between two nodes. This makes sense as the function neither create ids
    internally (I believe) nor exposes the newly-created edge id to the outside (like `add_node`
    does) so it's not possible to reference back to an edge after its construction.

Do you think 1 & 2 would be features worth adding and, if yes, would you accept external contributions to your library? Thanks a lot for your time! 😸

**Comment by octavonce** [comment]
@adinapoli-mndc Hi there and thank you for the feedback!

```
It would be very nice to be able to have edges as "first class" citizens of the library. At the
moment one can only add a "plain" edge or a weighted one, but using an f32 is a bit
limiting, as users might want to embed arbitrary metadata at the edge level. Have you ever
thought about parametrising your Graph over some edge type E? If so, how did it go?
```
I had this argument with myself a couple of times. The only problem I see with this approach is that users who do not require metadata also have to provide a metadata paremeter. While a user requiring metadata can just create a wrapper type containing both the data and the metadata. However, this is at a vertex level. 

Edge level metadata would be nice but has the same problem.

The mission of this library is to be as easy to use as possible, even if this means not having all of the common features one finds in a graph library.

However, I do agree that maybe an f32 is not exactly the best type to use as the weight of the graph. 

```
In some circumstances, it might be necessary to allow parallel edges between nodes. At
the moment, if I understand correctly, add_edge is idempotent and cannot create more
than one edge between two nodes. This makes sense as the function neither create ids
internally (I believe) nor exposes the newly-created edge id to the outside (like add_node
does) so it's not possible to reference back to an edge after its construction.
```
I haven't really thought about this one. This can be done how you said, by exposing an edge id and I believe it would be a good idea. 

`Do you think 1 & 2 would be features worth adding and, if yes, would you accept external contributions to your library? Thanks a lot for your time! `  - I think the first point steers away from the library's mission but the second point seems like it would be a good addition. So, you are welcome to open a PR!

**Comment by adinapoli-mndc** [comment]
Hey @octavonce , thanks for the quick reply!

> I had this argument with myself a couple of times. The only problem I see with this approach is that users who do not require metadata also have to provide a metadata paremeter. While a user requiring metadata can just create a wrapper type containing both the data and the metadata. However, this is at a vertex level.

Yes, I totally see what you mean, it's always a tradeoff between ease of use and features 😉 Here, though, I don't see a particular problem. Surely I am being naive, but I would have thought that you can easily create that wrapper _in the library itself_, exposing it to the users for free. What I mean is this: you can create a more general `AbstractGraph` type, which is parametric over `V,E`, and then have your simplified `Graph<E = f32>` that you expose (just like now). I think this would be largely the same API-ergonomics-wise, but would support more use cases.

> I think the first point steers away from the library's mission but the second point seems like it would be a good addition. So, you are welcome to open a PR!

That's great to hear, thank you!

**Comment by micouy** [comment]
I agree with @adinapoli-mndc. Such solution doesn't harm anybody and it enables you to do much more things with this library. It's actually a feature I'd need `graphlib` to have to use it in my project.

Another argument for it is that having a second param is not that uncommon or difficult to deal with. `HashMap<K, V>` is one example.
