### ISSUE TITLE
Topo method panics even if graph is acyclic

### ISSUE THREAD

**Issue by hydrogenoxide** [purpleprotocol/graphlib#32]
Hey,

There seems to be a bug in the topo method.
If you remove any edges such that the graph is acyclic, the topo method will still panic if the graph was cyclic before.

An example:
```rust
use graphlib::*;

fn main() {
    let mut g = Graph::new();

    let id1 = g.add_vertex(1);
    let id2 = g.add_vertex(2);
    let id3 = g.add_vertex(3);

    g.add_edge(&id1, &id2).expect("Couldn't add edge!");
    g.add_edge(&id2, &id3).expect("Couldn't add edge!");

    println!("g cyclic: {}", g.is_cyclic());

    if g.is_cyclic() == false {
        println!("g in topological ordering:");
        for n in g.topo() {
            println!("{}", g.fetch(&n).unwrap());
        }
    }

    g.add_edge(&id3, &id1).expect("Couldn't add edge!");
    println!("g cyclic: {}", g.is_cyclic());

    g.remove_edge(&id3, &id1);
    println!("g cyclic: {}", g.is_cyclic());

    if g.is_cyclic() == false {
        println!("g in topological ordering:");
        for n in g.topo() {
            println!("{}", g.fetch(&n).unwrap());
        }
    }
}
```

Expected behaviour: Print a topological sorting twice and return normally.
Observed behaviour: Panic 'graph contains cycle(s)' even though `g.is_cyclic()` returns false
Rust version: 1.38 on stable-x86_64-unknown-linux-gnu
graphlib version: 0.5.2

**Comment by octavonce** [comment]
@hydrogenoxide Hi and thank you very much for submitting a bug report! 

@garyanaplan ~~Do you have any input on this? It seems to me that the reason for this is the cache not being updated properly~~.
