### ISSUE TITLE
Add Directed Acyclic Graphs or insert with cycle check

### ISSUE THREAD

**Issue by micouy** [purpleprotocol/graphlib#42]
It would be cool to have acyclic graphs without having to add the edge and checking for cycles.

**Comment by octavonce** [comment]
@micouy Something like `Graph::add_edge_check_cyclic()` that fails if the edge creates a cycle?

**Comment by micouy** [comment]
Yes, but by fail I mean return a result, not panic. Or it could be a `DAG` type with checks by default in `DAG::insert()`. I think the latter could actually be more efficient. See, you only need to check for cycles if you add an edge and have no more info about it. But the `DAG` type could have a method like `DAG::attach()` which would take the id of a node you want to attach something to, a new node and edge. You don't have to check for cycles because they just can't occur in such situation. The same is true for the other direction (when you attach an existing node to a new one).

**Comment by octavonce** [comment]
@micouy While I do understand your point and somewhat agree with it, it would require writing another type altogether with most of the same methods but differing apis. For now, a method that checks for cycles and returns a `Result` seems a good and low-effort way to add a `DAG` contract to `Graph`s.

**Comment by micouy** [comment]
I agree, but there's an issue with that. I'm not sure if the `Graph` type supports directed edges. If not, just adding cycle checks is pretty useless.

**Comment by octavonce** [comment]
@micouy All edges are currently directed, it doesn't support undirected edges. In order to have an undirected graph, one can add for each edge `A` to `B` a pair edge from `B` to `A` which intrinsically has cycles.
