### ISSUE TITLE
It sometimes fails to find cycles

### ISSUE THREAD

**Issue by octavonce** [purpleprotocol/graphlib#9]
For some reason, in some instances the method for checking cycles fails to do so. This should be investigated.

**Comment by Dynisious** [comment]
Hey, does anyone mind if I take a swing at this issue?

**Comment by Dynisious** [comment]
Additionally I have a solution in mind but it would involve moving `is_cyclic` from `Dfs` to `Bfs`. Is there any issues with me doing that?

**Comment by octavonce** [comment]
@Dynisious Hi! You are welcome to do so!

**Comment by octavonce** [comment]
Fixed in #19
